#!/usr/bin/env bash
# Redirect_me is redirecting
sudo apt update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i '/listen 80 default_server/a \\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/error404.html
sudo sed -i '/listen 80 default_server/a \\terror_page 404 /error404.html;\n' /etc/nginx/sites-available/default
sudo service nginx restart