#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
sudo apt-get update
sudo apt-get -y install haproxy
sudo sed -i '/errorfile 504/a frontend http_front\n\tbind *:80\n\tstats uri /haproxy?stats\n\tdefault_backend http_back\n\nbackend http_back\n\tbalance roundrobin\n\tserver web1 35.196.207.6:80 check\n\tserver web2 18.212.234.152:80 check' /etc/haproxy/haproxy.cfg
service haproxy restart