#!/usr/bin/env bash
# configures the container as nginx user

sudo chown -R nginx:nginx /etc/nginx/
sudo chmod 644 /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-available/default
sudo pkill apache2
sudo -u nginx service nginx start
